### ISSUE TITLE
求助，请问为什么会出现这个情况，这个问题该如何解决

### ISSUE THREAD

**Issue by Jonyond-lin** [lanmengyiyu/yolov5-deepmar#10]
![4 0](https://user-images.githubusercontent.com/36891952/130041395-1ef90bb9-3112-4c7b-9ffe-c92b355f2ffa.png)
这是我运行代码生成的视频文件，使用的是
parser.add_argument('--attributes', type=str, default='deepmar/attribute_list.pickle',
                        help='Chinese attribute list path')

**Comment by lanmengyiyu** [comment]
该一下字体就好了

**Comment by lanmengyiyu** [comment]
> 



> ![4 0](https://user-images.githubusercontent.com/36891952/130041395-1ef90bb9-3112-4c7b-9ffe-c92b355f2ffa.png) 这是我运行代码生成的视频文件，使用的是 parser.add_argument('--attributes', type=str, default='deepmar/attribute_list.pickle', help='Chinese attribute list path')

改一下字体就好了
