### ISSUE TITLE
Where is the file deepmar_statedict.pth

### ISSUE THREAD

**Issue by mowkee** [lanmengyiyu/yolov5-deepmar#2]
Where can I get this file?

**Comment by lanmengyiyu** [comment]
> Where can I get this file?

This file was trained by deepmar, I will share a google drive link for you.
1. https://drive.google.com/drive/folders/11qr6Y2c62NzM3BN_011oXLHietiw5tbi?usp=sharing
2. https://drive.google.com/drive/folders/1r08uwmB3QeOnwkhOupZ0UCC1TIaGybOK?usp=sharing
3. https://drive.google.com/drive/folders/1KRoWa-VJwgOxWXgywuzwFaq95wDd0QnJ?usp=sharing

**Comment by mowkee** [comment]
Thanks for the prompt reply. I'll test them soon and update you if there's any other issue.

**Comment by mowkee** [comment]
The weight files are working. I'll close this issue but the code had bugs and I had to debug it myself. I mean it's not ready to run directly in the current state.

**Comment by lanmengyiyu** [comment]
This may be a problem of your environment. You can run directly on the colab.
