### ISSUE TITLE
Any info about the performance of the deepmar model

### ISSUE THREAD

**Issue by mowkee** [lanmengyiyu/yolov5-deepmar#3]
I successfully ran the code but it runs very slow. I am using a Nvidia GeForce GTX 1060 and CUDA 10.2. What is your testing environment and what was the speed?

**Comment by lanmengyiyu** [comment]
The slow speed is mainly due to the Chinese font writing. You can comment out the image format conversion.

**Comment by GarethWright** [comment]
I removed the font and this made little difference.  After commenting out the deepmar inference it was 18fps on a 1080p rtsp source.

Adding deepmar back in slows it back down to 3 seconds per frame on 1080TI 11GB.

**Comment by lanmengyiyu** [comment]
Mainly the time taken by the image conversion
