### ISSUE TITLE
Could U please provide the file ...?

### ISSUE THREAD

**Issue by dearwsj** [lanmengyiyu/yolov5-deepmar#4]
/content/drive/My Drive/deepmar weight/deepmar_statedict.pth
Thanks :)

**Comment by lanmengyiyu** [comment]
This file was trained by deepmar, I will share a google drive link for you.
https://drive.google.com/drive/folders/11qr6Y2c62NzM3BN_011oXLHietiw5tbi?usp=sharing
https://drive.google.com/drive/folders/1r08uwmB3QeOnwkhOupZ0UCC1TIaGybOK?usp=sharing
https://drive.google.com/drive/folders/1KRoWa-VJwgOxWXgywuzwFaq95wDd0QnJ?usp=sharing
