### ISSUE TITLE
incomplete attributes 

### ISSUE THREAD

**Issue by ashutosh2909** [lanmengyiyu/yolov5-deepmar#5]
First of all thanks for this wonderful work!
I tried replicating this project with CPU support, the new video which gets created inside output folder is getting weird incomplete attribute. Please refer the attached image for reference.
Could you help me get the correct attribute (I am using attribute_list.pickle).
![image](https://user-images.githubusercontent.com/51769717/109178923-5ee54d00-77af-11eb-8968-c360d51de149.png)

if anyone could tell me what changes do i need to make in detect.py then it would suffice my need.

**Comment by lanmengyiyu** [comment]
The current property is Chinese, you need to convert it to English, and change the font smaller

**Comment by ashutosh2909** [comment]
I think some change in code is also required, I guess it is only showing the first character of every attribute.
How can i adapt this code to get the result like what is shown in demo video.
I am not expert in this, so somewhat descriptive instruction would be very much appreciated.

**Comment by lanmengyiyu** [comment]
just use zhe attribute_list.pickle instead of attribute_list_Chinese.pkl
