### ISSUE TITLE
Something about fontsize

### ISSUE THREAD

**Issue by Jonyond-lin** [lanmengyiyu/yolov5-deepmar#8]
Thank you guys for made such a good job, however, when I run the code and get the visualized result, I found the labels are different with what I saw in your youtube channel. what I mean is, I got the Chinese labels and look too large.
![fontsizeError](https://user-images.githubusercontent.com/36891952/127418913-9f943f14-22b9-4b6d-9add-227b32d729ed.png)

May I know the way to change the text into English or made the fontsize smaller?

**Comment by lanmengyiyu** [comment]
https://github.com/lanmengyiyu/yolov5-deepmar/blob/master/detect.py#L39

**Comment by Jonyond-lin** [comment]
> https://github.com/lanmengyiyu/yolov5-deepmar/blob/master/detect.py#L39

OK！I got it! Thank you !
